// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.2
// source: product/product.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductServiceClient interface {
	GetProductQuantityById(ctx context.Context, in *GetProductQuantityByIdRequest, opts ...grpc.CallOption) (*GetProductQuantityResponse, error)
	GetProductQuantityByName(ctx context.Context, in *GetProductQuantityByNameRequest, opts ...grpc.CallOption) (*GetProductQuantityResponse, error)
	AddProductQuantity(ctx context.Context, in *AddProductQuantityRequest, opts ...grpc.CallOption) (*AddProductQuantityResponse, error)
	RemoveProductQuantity(ctx context.Context, in *RemoveProductQuantityRequest, opts ...grpc.CallOption) (*RemoveProductQuantityResponse, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) GetProductQuantityById(ctx context.Context, in *GetProductQuantityByIdRequest, opts ...grpc.CallOption) (*GetProductQuantityResponse, error) {
	out := new(GetProductQuantityResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetProductQuantityById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProductQuantityByName(ctx context.Context, in *GetProductQuantityByNameRequest, opts ...grpc.CallOption) (*GetProductQuantityResponse, error) {
	out := new(GetProductQuantityResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetProductQuantityByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) AddProductQuantity(ctx context.Context, in *AddProductQuantityRequest, opts ...grpc.CallOption) (*AddProductQuantityResponse, error) {
	out := new(AddProductQuantityResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/AddProductQuantity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) RemoveProductQuantity(ctx context.Context, in *RemoveProductQuantityRequest, opts ...grpc.CallOption) (*RemoveProductQuantityResponse, error) {
	out := new(RemoveProductQuantityResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/RemoveProductQuantity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
// All implementations must embed UnimplementedProductServiceServer
// for forward compatibility
type ProductServiceServer interface {
	GetProductQuantityById(context.Context, *GetProductQuantityByIdRequest) (*GetProductQuantityResponse, error)
	GetProductQuantityByName(context.Context, *GetProductQuantityByNameRequest) (*GetProductQuantityResponse, error)
	AddProductQuantity(context.Context, *AddProductQuantityRequest) (*AddProductQuantityResponse, error)
	RemoveProductQuantity(context.Context, *RemoveProductQuantityRequest) (*RemoveProductQuantityResponse, error)
	mustEmbedUnimplementedProductServiceServer()
}

// UnimplementedProductServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (UnimplementedProductServiceServer) GetProductQuantityById(context.Context, *GetProductQuantityByIdRequest) (*GetProductQuantityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductQuantityById not implemented")
}
func (UnimplementedProductServiceServer) GetProductQuantityByName(context.Context, *GetProductQuantityByNameRequest) (*GetProductQuantityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductQuantityByName not implemented")
}
func (UnimplementedProductServiceServer) AddProductQuantity(context.Context, *AddProductQuantityRequest) (*AddProductQuantityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProductQuantity not implemented")
}
func (UnimplementedProductServiceServer) RemoveProductQuantity(context.Context, *RemoveProductQuantityRequest) (*RemoveProductQuantityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveProductQuantity not implemented")
}
func (UnimplementedProductServiceServer) mustEmbedUnimplementedProductServiceServer() {}

// UnsafeProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServiceServer will
// result in compilation errors.
type UnsafeProductServiceServer interface {
	mustEmbedUnimplementedProductServiceServer()
}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

func _ProductService_GetProductQuantityById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductQuantityByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductQuantityById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetProductQuantityById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductQuantityById(ctx, req.(*GetProductQuantityByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProductQuantityByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductQuantityByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductQuantityByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetProductQuantityByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductQuantityByName(ctx, req.(*GetProductQuantityByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_AddProductQuantity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductQuantityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).AddProductQuantity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/AddProductQuantity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).AddProductQuantity(ctx, req.(*AddProductQuantityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_RemoveProductQuantity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveProductQuantityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).RemoveProductQuantity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/RemoveProductQuantity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).RemoveProductQuantity(ctx, req.(*RemoveProductQuantityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductService_ServiceDesc is the grpc.ServiceDesc for ProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductQuantityById",
			Handler:    _ProductService_GetProductQuantityById_Handler,
		},
		{
			MethodName: "GetProductQuantityByName",
			Handler:    _ProductService_GetProductQuantityByName_Handler,
		},
		{
			MethodName: "AddProductQuantity",
			Handler:    _ProductService_AddProductQuantity_Handler,
		},
		{
			MethodName: "RemoveProductQuantity",
			Handler:    _ProductService_RemoveProductQuantity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product/product.proto",
}
